# DDO Data Platform: Github Branch Protection
# ATTENTION: Changing this is NOT RECOMMENDED as it can have unintended consequences. 

name: Configure Branch Protection

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - '.github/workflows/configure-branch-protection.yml'

jobs:
  configure-protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.name;
            
            // Apply to main and development branches
            for (const branch of ['main', 'development']) {
              console.log(`Configuring protection for ${branch} branch`);
              try {
                await github.rest.repos.updateBranchProtection({
                  owner: owner,
                  repo: repo,
                  branch: branch,
                  required_status_checks: {
                    strict: true,
                    contexts: ['code-quality', 'integration-tests']
                  },
                  enforce_admins: false,
                  required_pull_request_reviews: {
                    required_approving_review_count: 1,
                    dismiss_stale_reviews: true,
                    require_code_owner_reviews: false
                  },
                  restrictions: null,
                  allow_force_pushes: false,
                  allow_deletions: false,
                  required_linear_history: true,
                  allow_fork_syncing: true
                });
                console.log(`Successfully configured ${branch} branch protection`);
              } catch (error) {
                console.log(`Error configuring ${branch} branch: ${error.message}`);
                throw error;
              }
            }
