# DDO Data Platform: Github Branch Protection
# ATTENTION: Changing this is NOT RECOMMENDED as it can have unintended consequences. 

name: Configure Branch Protection

on:
  workflow_dispatch:

jobs:
  configure-protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            // Protect main branch
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.name,
              branch: 'main',
              enforce_admins: false,
              required_pull_request_reviews: {
                required_approving_review_count: 1
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false
            });
            
            // Protect development branch
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.name,
              branch: 'development',
              enforce_admins: false,
              required_pull_request_reviews: {
                required_approving_review_count: 1
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false
            });
