# DDO Data Platform: Github Branch Protection
# ATTENTION: Changing this is NOT RECOMMENDED as it can have unintended consequences. 

name: Branch Protection

on:
  workflow_dispatch:

jobs:
  protect-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            console.log('Repository:', process.env.GITHUB_REPOSITORY);
            
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            
            for (const branch of ['main', 'development']) {
              await github.request(
                'PUT /repos/{owner}/{repo}/branches/{branch}/protection',
                {
                  owner,
                  repo,
                  branch,
                  required_status_checks: null,
                  enforce_admins: false,
                  required_pull_request_reviews: {
                    required_approving_review_count: 1,
                    dismiss_stale_reviews: true
                  },
                  restrictions: null
                }
              );
            }
